language: node_js
node_js:
  - 0.10
before_install:
  - wget http://phantomjs.googlecode.com/files/phantomjs-1.9.2-linux-x86_64.tar.bz2
  - tar -xf phantomjs-1.9.2-linux-x86_64.tar.bz2
  - sudo rm -rf /usr/local/phantomjs
  - sudo mv phantomjs-1.9.2-linux-x86_64/bin/phantomjs /usr/local/phantomjs

script:
  - which phantomjs
  - phantomjs -v
  # - "cake test"
